# fly.toml app configuration file generated for pms-docker on 2025-03-09T17:49:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pms-docker'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 32400
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
